"""Initial migration

Revision ID: 0e227c90cf53
Revises: 
Create Date: 2026-06-14 20:40:26.921104

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0e227c90cf53'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sessions_cache',
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('circuit_name', sa.String(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('api_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('cached_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_index(op.f('ix_sessions_cache_session_id'), 'sessions_cache', ['session_id'], unique=False)
    op.create_table('users',
    sa.Column('clerk_user_id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('clerk_user_id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_users_clerk_user_id'), 'users', ['clerk_user_id'], unique=False)
    op.create_table('laps_cache',
    sa.Column('lap_id', sa.String(), nullable=False),
    sa.Column('driver_number', sa.Integer(), nullable=True),
    sa.Column('session_id', sa.String(), nullable=True),
    sa.Column('downsampled_telemetry_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('cached_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['sessions_cache.session_id'], ),
    sa.PrimaryKeyConstraint('lap_id')
    )
    op.create_index(op.f('ix_laps_cache_lap_id'), 'laps_cache', ['lap_id'], unique=False)
    op.create_table('user_bookmarks',
    sa.Column('bookmark_id', sa.String(), nullable=False),
    sa.Column('clerk_user_id', sa.String(), nullable=True),
    sa.Column('lap_id_1', sa.String(), nullable=True),
    sa.Column('lap_id_2', sa.String(), nullable=True),
    sa.Column('custom_note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['clerk_user_id'], ['users.clerk_user_id'], ),
    sa.PrimaryKeyConstraint('bookmark_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_bookmarks')
    op.drop_index(op.f('ix_laps_cache_lap_id'), table_name='laps_cache')
    op.drop_table('laps_cache')
    op.drop_index(op.f('ix_users_clerk_user_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_sessions_cache_session_id'), table_name='sessions_cache')
    op.drop_table('sessions_cache')
    # ### end Alembic commands ###
